//
//  LL_Ideas.swift
//  RelationshipHelper
//
//  Created by Jonathan Goldson on 5/9/21.
//

import Foundation

struct LL_Ideas {
    
    let wordsOfAffirmation = [
        "You are so special to me",
        "After all of this time, I'm still so crazy for you",
        "It really impressed me when you…",
        "I couldn't have done ____ without you",
        "You inspire me to…",
        "Did I tell you how grateful I am that you are my partner?",
        "You deserve all of the praise at work. I see how hard you've been working",
        "I just wanted to let you know I'm proud of you",
        "I really appreciate you when you do...",
        "I am here if you need me. I'm always in your corner supporting you",
        "I feel so loved when you...",
        "I am proud of you because...",
        "I want to take the time to thank you for how hard you work around our home",
        "You look amazing. Is that a new outfit?",
        "I am proud of you for always trying your best, whatever it is",
        "It makes my heart melt watching you take care of ____",
        "I value you doing _____ when you are tired",
        "Thank you for being so sweet and loving to my family and friends",
        "I'm the happiest when you make me laugh",
        "You have the cutest crinkles when you smile",
        "I find you so attractive and gorgeous",
        "I'm lucky that you are my partner",
        "I love our beautiful life together",
        "I love how your eyes sparkle when you...",
        "Thank you for making me feel safe and loved",
        "You did such a great job doing ____. Tell me more about it"
    ]
    let physicalTouch = [
        "Take a bath together",
        "Hold their hand often",
        "Hug them from behind",
        "Sneak a kiss randomly",
        "Give them a massage",
        "Play with their hair",
        "Play footsie",
        "Put your hand on their leg when you’re sitting next to each other",
        "Cuddle in bed in the morning for a few minutes before getting up",
        "Shower together and wash their back with an added massage",
        "Initiate sex",
        "Sit close to them on the couch or at a restaurant",
        "Kiss them passionately",
        "Cuddle while you sleep",
        "Hold hands while you’re falling asleep",
        "Rub their arm while you’re talking",
        "Accept their affection and physical touch",
        "Rub their back",
        "Cuddle while you’re talking",
        "Swat their butt while you’re walking past them",
        "Share a long hug",
        "Squeeze their hand or rub their thumb when you’re holding hands",
        "Take dancing lessons together in the community or using a YouTube tutorial",
        "Cuddle them at bedtime to help them fall asleep",
        "Wrap them in a hug with a towel fresh from the dryer as they get out of the shower",
        "Kiss them on the forehead",
        "Sneak kisses when you hit a red light while driving"
    ]
    let actsOfService = [
        "Pay a bill before your spouse gets to it",
        "Make breakfast in the morning",
        "Have their clothes washed, folded and put away",
        "Make their favorite treat",
        "Help with one of their chores",
        "Pack their lunch for the day",
        "Make their cup of coffee in the morning",
        "Wash their car",
        "Take on chores that they hate. Scheduling appointments, etc",
        "Fill their car with gas",
        "Help them with a project they’re working on… could be household or work",
        "Take the kids to school/daycare on a day that they’re supposed to",
        "Do the dishes/put them away",
        "Ask: What can I help you with?",
        "Make the bed",
        "Match their socks",
        "Pick up their favorite snacks from the store",
        "Ask: What can I do to make your day better today?",
        "Plan a date",
        "Ask if they want a snack or drink while you’re up",
        "Make their favorite meal",
        "Mow the lawn or have it mowed",
        "Clean up dinner",
        "Buy their toiletries when they’re getting low without them having to ask",
        "Get up with the kids and let your spouse sleep in",
        "Make a music playlist and share it with them",
        "Change the sheets",
        "Complete a house project that’s been on their list for a long time",
        "Complete an errand that they hate",
        "Make a podcast playlist for them",
        "Toss their towel in the dryer while they shower so they have a warm towel to use",
        "Grocery shop for the house",
        "Make their plate at meals",
        "Get a sitter and plan a surprise date night",
        "Bring them breakfast in bed",
        "Pick up an area of the house that drives them nuts",
        "Go to one of their sporting events/hobbies to watch",
        "Start their car before it’s time to leave so it’s warm or cool",
        "Plan meals for the week",
        "Help with something without being asked",
        "Bring the trashcan in from the curb",
        "Schedule their haircut, dentist appointments, etc",
        "Clean their shoes with a magic eraser to make them look new again",
        "Drop off/Pick up their clothes from the dry cleaner",
        "Organize the pantry",
        "When they ask for something do it right then or shortly after",
        "Help them do something nice for someone they care about",
        "Get them a snack when you get one for yourself",
        "Leave a joke or love note in their lunch, travel bag, gym bag, desk or wherever!",
        "If you’re out running errands, call or text asking if you can pick anything up for them",
        "Handle the logistics of a weekend away/plan a trip",
        "Clean out/organize their inbox"
    ]
    
    let qualityTime = [
        "Get lost in IKEA",
        "At home couple’s massage (make it legit – soft music, massage oil & 1 hour commitment!)",
        "Window shop, or actual shopping day",
        "Create a DIY game to play (DIY Monopoly, Scategories or C.A.H)",
        "Go to the county fair (watch people get sick on the rides instead!)",
        "Go sightseeing (nearby city/town/park)",
        "Attend a trivia night",
        "Share your thoughts on book titles at a bookstore",
        "Create a meal from kitchen scraps (more so quirky and fun than appetizing)",
        "Play the Alphabet game (Anywhere, not just on the road)",
        "Karaoke night",
        "Volunteer for the day (soup kitchen, humane society, animal shelter!)",
        "Throw a dance party, or DIY dance lesson (just the two of you!)",
        "Free zoo days (offered select days throughout the year!)",
        "Browse the farmer’s market",
        "Play the list game (“Ex: 25 things on your bucket list in the next 5 years” in 60 seconds)",
        "See who can stay up all night the longest (not advised to do on a work night!)",
        "Take a scenic drive",
        "Have a picnic",
        "Play pretend “real estate” online (pretend you are in the market for a house – pick a budget and location – each narrow down to 1 place and come to a compromise)",
        "Rearrange your furniture together",
        "Play the “I Spy” game (at a park, walking around a city or people watching!)",
        "Ghost hunt at your local cemetery",
        "Create a scavenger hunt",
        "Play a sport together",
        "Release your inner child together (play on the playground!)",
        "Go stargazing",
        "Try Geocaching together",
        "Free movie on the lawn (or lake, park, free wherever!)",
        "Brewery or wine tour (some out there are free!)",
        "Game night (with or without friends!)",
        "Walk through local gardens or arboretum",
        "Day at the beach/on the lake/along the river",
        "Take a walk/bike ride",
        "Hike nearby trails",
        "Open houses or estate sales (walk through, pretend you’re interested)",
        "Build an epic living room fort",
        "Free ice cream or smoothie days (check local listings!)",
        "Browse through a flea market",
        "Go tubing down a river",
        "Go to the dog park",
        "Camp in the backyard",
        "Attend an arts & crafts festival (check your nearest listings!)",
        "Reverse strip poker (you add on rather than take off)",
        "Go fishing",
        "Watch the sunrise or sunset",
        "Read a book together (to each other, aloud, taking turns)",
        "Video game battle (Mario Kart, Super Mario, or Wii)"
    ]
    
    let receivingGifts = [
        "Bring them their favorite flowers, just because",
        "Buy them something they’ve been wanting for awhile",
        "Send them a surprise package at work",
        "Make them a mix CD/Playlist and explain why you chose each song for them",
        "Sign them up for a class they’ve been wanting to take",
        "Buy them some chocolate or how about hand-making some chocolate dipped strawberries?",
        "Frame a recent (and cute) photo of the two of you together and wrap it up extra pretty",
        "Buy them a massage oil candle",
        "Buy (or make) them an artsy water bottle",
        "Buy them a scratch map to mark all the places you've been together",
        "Buy them a new board game you can play together",
        "Buy them a new book, or find one you think they'll love from the library"
    ]
    
}
